# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: claude
compress_threshold: 140000
save: true
save_session: true
clients:
- type: claude
  api_key: #add key here
- type: openai
  api_key: #add key here
rag_top_k: 5
